---
- name: Verify that backup directory exists
  file:
    path: "{{ lookup('env', 'POET_PROJECT_PATH') }}/cellar/backup/database/"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    mode: 0700

- name: Dump the database "{{ lookup('env', 'POET_DATABASE_NAME') }}"
  postgresql_db:
    name: "{{ lookup('env', 'POET_DATABASE_NAME') }}"
    login_user: "{{ lookup('env', 'POET_DATABASE_USER') }}"
    login_password: "{{ lookup('env', 'POET_DATABASE_PASSWORD') }}"
    state: dump
    target: "{{ lookup('env', 'POET_PROJECT_PATH') }}/cellar/backup/database/{{ lookup('env', 'POET_DATABASE_NAME') }}-{{ lookup('pipe','date +%Y%m%d.%H%M') }}-{{ lookup('env', 'POET_VERSION') }}-sql.gz"
    dump_extra_args: --no-owner --no-privileges
