---
- name: Dump the database "{{ lookup('env', 'POET_DATABASE_NAME') }}"
  postgresql_db:
    name: "{{ lookup('env', 'POET_DATABASE_NAME') }}"
    login_user: "{{ lookup('env', 'POET_DATABASE_USER') }}"
    login_password: "{{ lookup('env', 'POET_DATABASE_PASSWORD') }}"
    state: dump
    target: "{{ lookup('env', 'POET_PROJECT_PATH') }}/www/backup/database/{{ lookup('env', 'POET_DATABASE_NAME') }}-{{ lookup('pipe','date +%Y%m%d.%H%M') }}-{{ lookup('env', 'POET_VERSION') }}-sql.gz"
