---
- name: Dump the database
  postgresql_db:
    name: "{{ lookup('env', 'POET_DATABASE_NAME') }}"
    state: dump
    target: "{{ lookup('env', 'POET_PROJECT_PATH' }}/www/backup/database/{{ lookup('env', 'POET_DATABASE_NAME') }}.{{ lookup('pipe','date +%Y%m%d-%H%M')}}.{{ lookup('env', 'POET_VERSION') }}.sql.gz