---
- name: "Test Connection"
  block:
    - name: "No su"
      command: /usr/bin/whoami
    - name: "su to root"
      command: /usr/bin/whoami
      become: True
  rescue:
    - debug:
        msg: "Either the user is not set or the privileges do not allow escalation to root"